### ISSUE TITLE
启动服务器的代码未加入到项目中

### ISSUE THREAD

**Issue by featherJ** [aksdjfh/goal1.1#1]
如题，发现启动服务器的代码为一个单独的server.js文件，而不是以ts项目的形式存在。
启动项目后跑的仍然是School和Student的示例。

需要启动项目以后跑的是服务器而非School和Student的示例

**Comment by GoooodJob** [comment]
@featherJ 谢谢建议，更改了npm和本地vscode配置，现在可以通过vscode的debug console或npm start启动服务器
